server:
  port: 8080

spring:
  application:
    name: 'FoodTruckFinder'
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://postgres:5432/foodtruckfinder
    driverClassName: org.postgresql.Driver

springdoc:
  api-docs:
    path: /v1/api-docs

